name: test-rclone

on:
  workflow_dispatch:
    inputs:
      source_remote:
        description: 'Source rclone remote'
        required: true
        type: choice
        options:
          - gdrive1
          - gdrive3
          - 1drive
        default: 'gdrive1'
      source_path:
        description: 'Source path in selected remote'
        required: true
        default: 'VS_Stock/'
      destination_remote:
        description: 'Destination rclone remote'
        required: true
        type: choice
        options:
          - gdrive3
          - gdrive1
          - 1drive
        default: 'gdrive3'
      destination_path:
        description: 'Destination path in selected remote'
        required: true
        default: 'Mirror'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone

      - name: Configure rclone
        env:
          RCLONE_CONFIG_BASE64: ${{ secrets.RCLONE_CONFIG_BASE64_3 }}
        run: |
          mkdir -p ~/.config/rclone
          echo $RCLONE_CONFIG_BASE64 | base64 --decode > ~/.config/rclone/rclone.conf
          
        
      - name: Run Rclone Sync
        env:
          SOURCE_REMOTE: ${{ inputs.source_remote }}
          DESTINATION_REMOTE: ${{ inputs.destination_remote }}
        run: |
          set -o pipefail
          echo "Starting rclone copy from ${SOURCE_REMOTE}:${{ github.event.inputs.source_path }} to ${DESTINATION_REMOTE}:${{ github.event.inputs.destination_path }}"
          rclone copy "${SOURCE_REMOTE}:${{ github.event.inputs.source_path }}" "${DESTINATION_REMOTE}:${{ github.event.inputs.destination_path }}" \
            --drive-server-side-across-configs=true \
            --transfers 32 \
            --checkers 32 \
            --verbose \
            --stats 10s \
            --stats-one-line \
            2>&1 | tee rclone_log.txt

      - name: Send Telegram Notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          format: markdown
          message: |
            *Rclone Job Finished*
            Status: `${{ job.status }}`
            Source: `${{ inputs.source_remote }}:${{ github.event.inputs.source_path }}`
            Destination: `${{ inputs.destination_remote }}:${{ github.event.inputs.destination_path }}`
            
